### PR TITLE
2.2.0 release

### PR DESCRIPTION
**Pull request by GuidoMaggio**
### Covid19Mirai 2.2.0 (2020-09-04)
- Added Switzerland tab with maps at Kanton level (#20)
- Reviewed calculation and definition of Growth Factors (#122)
- Added new graph to Global page, selected top 10 in barplots

### CODE REVIEW

**Comment by StefGehring** [comment]
review:
general:
minor comment: Growth versus Prevalence Map not aligned (probably because nothing to select)
Swiss tab: 
suggestion: move the Swiss generic table to download down (just before the split by region table) -> consistency with other tabs.

**Comment by GuidoMaggio** [comment]
Thanks for the suggestions Stephanie. I have taken both of them in

Please have a look

**Comment by StefGehring** [comment]
the changes look good
Just wondering, if we should have some kind of parametrization to avoid this kind of display: (ex: France)
image

**Comment by GuidoMaggio** [comment]
Yes, possibly we should, however there is a note that says that all graphs are displayed despite some countries/regions do not provide the data required. For most of countries these graphs work
To be done another time

Thanks

**Pull request merged**
