### PR TITLE
Feature/59 negative in map

### PR DESCRIPTION
**Pull request by StefGehring**
as agreed set different color -grey for NA in new active mod_map.R (#59)

### CODE REVIEW

**Comment by GuidoMaggio** [comment]
It looks fine, I have verified on "New_Active", all other variables do not seem affected.
I have taken the chance to correct a text message

**Comment by riccardoporreca** [comment]
@GuidoMaggio @StefGehring , don't worry about the failure on the branch push: what matters is the pull request CI-CD, which is fine.

The problem with the branch is that the cached packages were installed for R 4.0 initially for the branch, but then the branch was being forced to R 3.6.3 with the merge from `develop`, which makes the cache inconsistent. This is a known issue, and is also mentioned in #75.

If this is a blocker for merging the PR let me know and I can do a quick trick

**Comment by riccardoporreca** [comment]
I am actually quickly fixing it as in #71, where we had the same issue

**Comment by riccardoporreca** [comment]
Fixed, this PR should be squash-merged to keep the commit history clean

**Pull request merged**
